improve jeka shell scripts

diff --git a/dev.jeka.core/src/main/shell/jeka2 b/dev.jeka.core/src/main/shell/jeka2
--- a/dev.jeka.core/src/main/shell/jeka2
+++ b/dev.jeka.core/src/main/shell/jeka2
@@ -1,21 +1,29 @@
 #!/bin/sh
 
 set -e
-#set -x
 
-
+declare LOG_DEBUG="true"
 declare DRY_RUN  # Debugging purpose
+
+declare GLOGAL_ARGS=$@  ## store in global variable to access within function
+
 declare JEKA_VERSION_PROP_NAME="jeka.java.version"
 declare JEKA_JAR_NAME="dev.jeka.jeka-core.jar"
+
 declare GLOBAL_PROP_FILE
 declare JEKA_USER_HOME
-#declare GLOBAL_ARGS="$@"
 declare BASE_DIR  # To find BASE_DIR/jeka/local.properties, BASE_DIR/jeka/def, ...
 declare CURRENT_SCRIPT_DIR
-declare LOG_DEBUG="on"
+declare WORKING_DIR=$(pwd)
+
+declare JDK_DOWNLOAD_DISTRIB="temurin"
+declare JDK_DOWNLOAD_LIBC_TYPE="glibc"  # default for linux, overridden for other os
+declare JDK_DOWNLOAD_FILE_TYPE="tar.gz" # overridden for *WIN os
+declare JDK_DOWNLOAD_OS
+declare JDK_DOWNLOAD_ARCH
 
 debug() {
-  if [ ! -z $"$LOG_DEBUG" ]; then
+  if [ -n "$LOG_DEBUG" ]; then
     echo "$1"
   fi
 }
@@ -23,12 +31,13 @@ debug() {
 download_and_unpack() {
   local url=$1
   local dir=$2
+  local file_type=$3  # 'zip' or 'tar.gz'
   local temp_file=$(mktemp)
   rm "$temp_file"
 
   ## download
   if [ -x "$(command -v curl)" ]; then
-    curl -sLf --fail --show-error -o "$temp_file" "$url"
+    curl -Lf --fail --show-error -o "$temp_file" "$url"
   elif [ -x "$(command -v wget)" ]; then
     wget -q -O "$temp_file" "$url"
   else
@@ -37,7 +46,8 @@ download_and_unpack() {
   fi
 
   ## unpack
-  if [[ "$url" == *.tar.gz ]]; then
+  if [ "$file_type" == "tar.gz" ]; then
+      mkdir -p "$dir"
       gzip -cd "$temp_file" | tar xf - -C "$dir"
   else
     unzip -qq -o "$temp_file" -d "$dir"
@@ -92,9 +102,9 @@ get_prop_value_from_base_dir() {
 
 # call `propJavaVersion currentDir`
 get_java_version_from_props() {
-  local base_dir=$1
+  local base_dir="$1"
   local version=$(get_prop_value_from_base_dir "$base_dir" "$JEKA_VERSION_PROP_NAME")
-  local trimmed_version=$(echo $value | sed 's/ //g')  # remove spaces
+  local trimmed_version=$(echo "$version" | sed 's/ //g')  # remove spaces
   echo $trimmed_version
 }
 
@@ -106,17 +116,18 @@ get_jdk_home_for_version() {
 
   # Look first in env variables
   local envValue=$(printenv "$prop_name")
-  if [ ! -z $envValue ]; then
+  if [ "$envValue" != "" ]; then
     echo $envValue
-    return
+    return 0
   fi
+
   # -- look for 'envVarified' name
   local env_var_name=$(get_env_var_name "$prop_name")
-  envValue=$(printenv "$env_var_name")
-  if [ ! -z $envValue ]; then
-    echo $envValue
-    return
-  fi
+  #envValue=$(printenv "env_var_name")
+  #if [ "$envValue" != "" ]; then
+  #  echo $envValue
+  #  return 0
+  #fi
 
   # Look in property files
   local path=$(get_prop_value_from_base_dir "$base_dir" "$prop_name")
@@ -159,7 +170,7 @@ substring_after_hash() {
 # Return the argument following '-r' arguments. Returns nothing if '-r' not found.
 # It takes an array as argument. If no arguments is passed, it use script exec args.
 get_remote_argument() {
-  for arg in $GLOBAL_ARGS; do
+  for arg in "$@"; do
     if [ "$previous" == "-r" ]; then
       echo $arg
       return
@@ -189,15 +200,33 @@ giturl_to_foldername() {
 
 ## return value in GLOBAL VAR : REMOTE_BASE_DIR
 compute_remote_base_dir() {
-    local remote_path_arg=$(get_remote_argument)
+
+    local remote_path_arg=$(get_remote_argument "$@")
     if [ -z "$remote_path_arg" ]; then
         REMOTE_BASE_DIR=""
+        debug "No -r argument detected"
         return 0  #no remote argument fount
     fi
     is_git_remote=$(is_git_url "$remote_path_arg")
     if [ "false" == "$is_git_remote" ]; then
-        REMOTE_BASE_DIR=$remote_path_arg
-        return 0
+      local target_base_dir
+      if [[ "$remote_path_arg" == /* ]]; then    # absolute path
+        target_base_dir="$remote_path_arg"
+        if [ ! -d "$target_base_dir" ]; then
+          echo "Directory $target_base_dir does not exist"
+          exit 1
+        fi
+      else  # relative path
+        target_base_dir="$WORKING_DIR"/"$remote_path_arg"
+        if [ ! -d "$target_base_dir" ]; then
+          echo "Directory $target_base_dir does not exist"
+          exit 1
+        fi
+        target_base_dir=$(cd "$target_base_dir" && pwd)  # normalize pass
+      fi
+      REMOTE_BASE_DIR="$target_base_dir"
+      debug "Remote '-r' argument detected with value $target_base_dir"
+      return 0
     fi
 
     ## Remote reference a git repo
@@ -292,68 +321,142 @@ get_jeka_classpath() {
   JEKA_CLASSPATH="$boot_dir_args$jar_file"
 }
 
+# call `get_or_download_jdk $javaVersion`. The result is set to DOWNLOAD_JDK_DIR var.
+get_or_download_jdk() {
+  local javaVersion="$1"
+  local specified_distrib=$(get_prop_value_from_base_dir "$BASE_DIR" "jeka.java.distrib")
+  if [ -n "$specified_distrib" ]; then
+    JDK_DOWNLOAD_DISTRIB="$specified_distrib"
+  fi
+  local jdk_cache_dir="$(get_cache_dir)/jdks/$JDK_DOWNLOAD_DISTRIB-$javaVersion"
+  if [ ! -d "$jdk_cache_dir" ]; then
+    if [ -z "$JDK_DOWNLOAD_OS" ]; then
+      echo "Unable to download JDK, unsupported Operating System: $(uname -s)" 1>&2
+      echo "You may workaround the problem in specifying a 'jeka.jdk.$javaVersion' env var or a property in ~/jeka/global.properties file." 1>&2
+      exit 1
+    fi
+    if [ -z "$JDK_DOWNLOAD_ARCH" ]; then
+      echo "Unable to download JDK, unsupported Architecture: $(uname -m)" 1>&2
+      echo "You may workaround the problem in specifying a 'jeka.jdk.$javaVersion' env var or property in ~/jeka/global.properties file." 1>&2
+      exit 1
+    fi
+    local download_url="https://api.foojay.io/disco/v3.0/directuris?distro=$JDK_DOWNLOAD_DISTRIB&javafx_bundled=false&libc_type=$JDK_DOWNLOAD_LIBC_TYPE&archive_type=$JDK_DOWNLOAD_FILE_TYPE&operating_system=$JDK_DOWNLOAD_OS&package_type=jdk&version=$javaVersion&architecture=$JDK_DOWNLOAD_ARCH&latest=available"
+    echo "Downloading JKD $JDK_DOWNLOAD_DISTRIB $javaVersion to $jdk_cache_dir. It may take a while..."
+    download_and_unpack "$download_url" "$jdk_cache_dir" "$JDK_DOWNLOAD_FILE_TYPE"
+    if [ "tar.gz" == "$JDK_DOWNLOAD_FILE_TYPE" ]; then
+      pushd "$jdk_cache_dir"
+      local nested_dir=$(find "." -mindepth 1 -maxdepth 1 -type d | head -n 1 | cut -c 3-)
+      popd
+      temp_dir=$(mktemp -d)
+      mv "$jdk_cache_dir"/"$nested_dir"/* "$temp_dir"
+      mv "$temp_dir"/* "$jdk_cache_dir"
+    fi
+  fi
+  DOWNLOAD_JDK_DIR=$jdk_cache_dir
+}
+
 ## -- script start here
 
-compute_remote_base_dir
+compute_remote_base_dir "$@"
 BASE_DIR="$REMOTE_BASE_DIR"
 if [ -z "$BASE_DIR" ]; then
   BASE_DIR=$(pwd)
 fi
 CURRENT_SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
 
-if [ -n "$JEKA_JDK" ] ; then
-  export JAVA_HOME=$JEKA_JDK
-  else
-    javaVersion=$(get_java_version_from_props "$BASE_DIR")
-    if [ ! -z $javaVersion ]; then
-      jdkPath=$(get_jdk_home_for_version "$BASE_DIR" $javaVersion)
-      if [ ! -z $jdkPath ]; then
-        export JAVA_HOME=$jdkPath
-      fi
-    fi
-fi
-
 # OS specific support.  $var _must_ be set to either true or false.
 cygwin=false;
 darwin=false;
 mingw=false
-case "`uname`" in
-  CYGWIN*) cygwin=true ;;
-  MINGW*) mingw=true;;
-  Darwin*) darwin=true
-           #
-           # Look for the Apple JDKs first to preserve the existing behaviour, and then look
-           # for the new JDKs provided by Oracle.
-           #
-           if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK ] ; then
-             #
-             # Apple JDKs
-             #
-             export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home
-           fi
+case "$(uname -s)" in
+  Linux*)
+    JDK_DOWNLOAD_OS="linux"
+    if [ -f /etc/alpine-release ]; then
+      JDK_DOWNLOAD_OS=alpine-linux
+    fi
+    ;;
+  CYGWIN*|MSYS*)
+    cygwin=true
+    JDK_DOWNLOAD_OS="windows"
+    JDK_DOWNLOAD_LIBC_TYPE="c_std_lib"
+    JDK_DOWNLOAD_FILE_TYPE="zip"
+    ;;
+  MINGW*)
+    mingw=true
+    JDK_DOWNLOAD_OS="windows"
+    JDK_DOWNLOAD_LIBC_TYPE="c_std_lib"
+    JDK_DOWNLOAD_FILE_TYPE="zip"
+    ;;
+  Darwin*)
+    darwin=true
+    JDK_DOWNLOAD_OS="mac"
+    JDK_DOWNLOAD_LIBC_TYPE="libc"; # necessary to download proper JDK
 
-           if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Java/JavaVirtualMachines/CurrentJDK ] ; then
-             #
-             # Apple JDKs
-             #
-             export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
-           fi
-
-           if [ -z "$JAVA_HOME" ] && [ -L "/Library/Java/JavaVirtualMachines/CurrentJDK" ] ; then
-             #
-             # Oracle JDKs
-             #
-             export JAVA_HOME=/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
-           fi
-
-           if [ -z "$JAVA_HOME" ] && [ -L "/usr/libexec/java_home" ]; then
-             #
-             # Apple JDKs
-             #
-             export JAVA_HOME=`/usr/libexec/java_home`
-           fi
-           ;;
+    # Look for the Apple JDKs first to preserve the existing behaviour, and then look
+    # for the new JDKs provided by Oracle.
+    if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK ] ; then
+      # Apple JDKs
+      JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home
+    fi
+    if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Java/JavaVirtualMachines/CurrentJDK ] ; then
+      # Apple JDK
+      JAVA_HOME=/System/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
+    fi
+    if [ -z "$JAVA_HOME" ] && [ -L "/Library/Java/JavaVirtualMachines/CurrentJDK" ] ; then
+      # Oracle JDK
+      JAVA_HOME=/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
+    fi
+    if [ -z "$JAVA_HOME" ] && [ -L "/usr/libexec/java_home" ]; then
+       # Apple JDKs
+       JAVA_HOME=`/usr/libexec/java_home`
+    fi
+    ;;
 esac
+
+case "$(uname -m)" in
+  i?86)
+    JDK_DOWNLOAD_ARCH="x32";;
+  x86_64|amd64)
+    JDK_DOWNLOAD_ARCH="x64";;
+  aarch64)
+    JDK_DOWNLOAD_ARCH="aarch64";;
+  armv7l)
+    JDK_DOWNLOAD_ARCH="arm";;
+  ppc64le)
+    JDK_DOWNLOAD_ARCH="ppc64le";;
+  s390x)
+    JDK_DOWNLOAD_ARCH="s390x";;
+  arm64)
+    JDK_DOWNLOAD_ARCH="arm64"
+    ;;
+  *)
+    ## AIX gives a machine ID for `uname -m` but it only supports ppc64
+    if [ "$os" = "aix" ]; then
+      JDK_DOWNLOAD_ARCH="ppc64"
+    else
+      JDK_DOWNLOAD_ARCH=""
+    fi
+    ;;
+esac
+
+# FIND JAVA HOME
+
+if [ -n "$JEKA_JDK" ] ; then
+  JAVA_HOME=$JEKA_JDK
+  else
+    javaVersion=$(get_java_version_from_props "$BASE_DIR")
+    if [ -n "$javaVersion" ]; then
+      jdkPath=$(get_jdk_home_for_version "$BASE_DIR" "$javaVersion")
+      debug "JDK HOME $javaVersion from env or props : $jdkPath "
+      if [ -z "$jdkPath" ]; then
+        get_or_download_jdk "$javaVersion"
+        if [ "$JDK_DOWNLOAD_OS" == "mac" ]; then
+          jdk_entry_sub_dir="/Contents/Home"
+        fi
+        JAVA_HOME="$DOWNLOAD_JDK_DIR$jdk_entry_sub_dir"
+      fi
+    fi
+fi
 
 if [ -z "$JAVA_HOME" ] ; then
   if [ -r /etc/gentoo-release ] ; then
@@ -435,11 +538,14 @@ if $cygwin; then
 fi
 
 ## Search if this is a call on remote base dir : result is stored REMOTE_BASE_DIR in case of.
-compute_remote_base_dir
+TARGET_BASE_DIR="$BASE_DIR"
+if [ -n "$REMOTE_BASE_DIR" ]; then
+  TARGET_BASE_DIR="$REMOTE_BASE_DIR"
+fi
 
 ## When debugging we don't want to execute Jeka
 if [ -z "$DRY_RUN" ]; then
   compute_jeka_distrib_dir "$BASE_DIR"
   get_jeka_classpath "$JEKA_DIST_DIR"
-  exec "$JAVACMD" $JEKA_OPTS -Djeka.current.basedir=$BASE_DIR -cp "$JEKA_CLASSPATH" "dev.jeka.core.tool.Main" "$@"
+  exec "$JAVACMD" $JEKA_OPTS -Djeka.current.basedir=$TARGET_BASE_DIR -cp "$JEKA_CLASSPATH" "dev.jeka.core.tool.Main" "$@"
 fi
diff --git a/dev.jeka.core/src/test/shell/jeka-test b/dev.jeka.core/src/test/shell/jeka-test
--- a/dev.jeka.core/src/test/shell/jeka-test
+++ b/dev.jeka.core/src/test/shell/jeka-test
@@ -32,6 +32,11 @@ echo "non.existing=$prop_value"
 prop_value=$(get_prop_value_from_base_dir "$SUB_DIR" "jeka.jdk.17")
 echo "jeka.jdk.17=$prop_value"
 
+# Test get_java_version_from_props
+prop_value=$(get_java_version_from_props "$SUB_DIR")
+echo "get_java_version_from_props = $prop_value"
+[ ! "$prop_value" == "17" ] && echo "Failure: function 'get_java_version_from_props' does not returns '17'" && exit 1
+
 # ------- JDK Location
 
 # Test JDK Path
@@ -50,7 +55,7 @@ echo "Git Cache Dir : $git_cache_dir"
 
 # ------- Remote script call
 
-remote_arg=$(get_remote_argument)
+remote_arg=$(get_remote_argument "$@")
 echo "Remote argument : '$remote_arg'"
 
 git_url="https://github.com/jeka-dev/template-examples.git#2.0"
